-- ==========================================
-- REDDIT SCHEMA
-- ==========================================

CREATE TABLE reddit_posts (
    -- Using TEXT for IDs as Reddit uses strings for IDs (e.g., 't3_xk3622')
    -- If using serial or UUID internally, we could make an internal 'id' and a 'reddit_id'
    -- For raw storage, using the platform's ID as PK is often easiest.
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    subreddit TEXT,
    
    -- NOTE: Upvotes are currently scraped as strings (e.g. "78" or "1.5k"). 
    -- If they contain "k" or "m", INTEGER will fail to cast directly. 
    -- We use INTEGER here assuming data cleaning before insertion, but if raw insertion 
    -- happens directly from the scraper, this might need to be TEXT or numeric parsing 
    -- should happen in the ETL.
    upvotes INTEGER, 
    
    body_text TEXT,
    
    -- Optional image URL
    image_url TEXT,
    
    -- Safety net for complete scraped object
    raw_json JSONB NOT NULL,
    
    -- Traceability
    scraped_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    source_query TEXT
);

CREATE TABLE reddit_comments (
    -- Reddit comment IDs are strings (e.g., 't1_ipxtyld')
    id TEXT PRIMARY KEY,
    
    -- Foreign key to always trace comment to its post, even if parent chain is broken
    post_id TEXT NOT NULL REFERENCES reddit_posts(id) ON DELETE CASCADE,
    
    -- Self-referencing FK for threaded replies. Nullable for top-level comments.
    parent_comment_id TEXT REFERENCES reddit_comments(id) ON DELETE SET NULL,
    
    author TEXT,
    
    -- Same note as reddit_posts.upvotes applies here
    upvotes INTEGER,
    
    -- Raw scraped text
    text TEXT,
    
    -- Cleaned text and flag, populated later in the pipeline
    cleaned_text TEXT,
    is_cleaned BOOLEAN DEFAULT FALSE,
    
    raw_json JSONB NOT NULL
);

-- ==========================================
-- YOUTUBE SCHEMA
-- ==========================================

CREATE TABLE youtube_videos (
    video_id TEXT PRIMARY KEY,
    title    TEXT NOT NULL,
    channel  TEXT,

    -- Scraper emits ISO 8601 timestamps (e.g. "2026-07-17T11:56:01Z") which
    -- cast cleanly to TIMESTAMPTZ. Watch for relative dates ("2 days ago")
    -- if other scrapers are plugged in later.
    published_date TIMESTAMP WITH TIME ZONE,

    -- BIGINT: view/like counts can exceed INT on viral content.
    view_count BIGINT,
    like_count BIGINT,

    -- TEXT: scraper emits "MM:SS" or "HH:MM:SS" strings (e.g. "13:16").
    -- If analytics on duration are needed, add a computed duration_seconds
    -- INTEGER column in a later migration.
    duration TEXT,

    url         TEXT NOT NULL,
    thumbnail   TEXT,
    description TEXT,

    -- ── Transcript metadata (no large text blobs here) ────────────
    -- The actual transcript text lives in transcript_chunks, not here.
    -- These columns describe what was captured so the pipeline can
    -- make decisions without touching the chunk table.

    -- BCP-47 language code of the scraped transcript (e.g. "en", "hin", "tam").
    -- NULL if no transcript was captured at all.
    transcript_language TEXT,

    -- TRUE when the video is non-English AND a translated English version was
    -- successfully obtained. FALSE when only the original language exists.
    -- Observed in sample data: translation fails with "Method Not Allowed"
    -- for several non-English videos, so this will often be FALSE even for
    -- non-English content. The ETL must detect empty-string translation
    -- responses and set this to FALSE rather than storing an empty chunk.
    is_translated     BOOLEAN NOT NULL DEFAULT FALSE,

    -- TRUE when the transcript was auto-generated by YouTube ASR rather than
    -- manually uploaded. Auto-generated transcripts tend to have higher error
    -- rates and no paragraph structure. Downstream cleaning should use this
    -- as a signal to apply heavier normalisation.
    -- NOTE: The current scraper does not expose this flag — it needs to read
    -- the 'trackKind' field from the YouTube Data API (value "asr" = auto).
    -- Until the scraper is updated, this defaults to FALSE and is unreliable.
    is_auto_generated BOOLEAN NOT NULL DEFAULT FALSE,

    -- Sum of word_count across all transcript_chunks rows for this video.
    -- Written by the ETL after all chunks are inserted (not computed on the fly).
    -- Used to identify extremely long videos before they enter the processing
    -- pipeline.
    --
    -- ⚠ PROCESSING COST RECOMMENDATION (not implemented yet):
    -- Query this field at the start of any claim-extraction job. For videos
    -- where transcript_word_count exceeds a threshold (e.g. 50 000 words,
    -- roughly 10+ hours of speech), consider one of these strategies:
    --
    --   (a) Hard cap: process only the first N chunks
    --       (e.g. N = 100, ~50 000 words). Mark remaining chunks with a
    --       future `processing_skipped` boolean column.
    --
    --   (b) Periodic sampling: process every K-th chunk to get a
    --       representative spread across the whole video.
    --
    --   (c) Priority windowing: process the first ~20%, a middle ~20%,
    --       and the last ~20% of chunks to capture intro, body, and
    --       conclusion — often where distinct claims are concentrated.
    --
    -- Whichever strategy is chosen belongs in processing-layer config,
    -- not in this schema. transcript_word_count is the gating signal.
    transcript_word_count INTEGER,

    -- Safety net: full scraped payload.
    raw_json JSONB NOT NULL,

    scraped_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_query TEXT
);


-- ─────────────────────────────────────────────────────────────
-- transcript_chunks
--
-- Stores transcript text as pre-chunked segments rather than one
-- large text blob on youtube_videos. Chunking happens in the ETL
-- at ingestion time, not lazily at processing time.
--
-- Target chunk size: 400–600 words, split on sentence boundaries
-- where possible to avoid cutting mid-claim.
--
-- If the transcript source provides timestamps (YouTube timedtext
-- API does), prefer time-boundary splits so start_time / end_time
-- are always populated and individual segments can be cited by
-- timestamp in downstream output.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE transcript_chunks (
    -- Surrogate BIGSERIAL PK: chunks have no stable natural identifier.
    -- Using (video_id, chunk_index) as a composite PK would complicate
    -- any future FK from a processing/claims table.
    id BIGSERIAL PRIMARY KEY,

    video_id TEXT NOT NULL REFERENCES youtube_videos(video_id) ON DELETE CASCADE,

    -- Zero-based sequential position within the video's transcript.
    -- The UNIQUE constraint on (video_id, chunk_index) enforces ordering
    -- integrity and prevents accidental duplicate inserts.
    chunk_index INTEGER NOT NULL,

    -- Offset in seconds from the start of the video.
    -- NUMERIC(10,3) stores millisecond-precision offsets (e.g. 12.340).
    -- NULL when no timestamp data is available from the transcript source.
    start_time NUMERIC(10, 3),
    end_time   NUMERIC(10, 3),

    -- Original-language chunk text.
    -- NULL when: (a) the video is in English (no translation split exists),
    -- or (b) only an English version was captured (translation failed).
    -- THIS COLUMN IS FOR CITATION AND DISPLAY ONLY.
    -- All downstream claim-extraction logic MUST read exclusively from
    -- chunk_text_english and must never branch on this field.
    chunk_text_original TEXT,

    -- English-language chunk text. NOT NULL — this is the canonical text
    -- for every downstream processing step without exception.
    --
    -- Population rules applied by the ETL:
    --   • Video originally in English        -> same text as original; chunk_text_original NULL.
    --   • Non-English, translation succeeded -> translated English text; chunk_text_original = original.
    --   • Non-English, translation failed    -> fallback to original-language text stored here;
    --                                           chunk_text_original = same text; is_translated = FALSE.
    --     (Allows processing to proceed, quality signal carried by is_translated on youtube_videos.)
    chunk_text_english TEXT NOT NULL,

    -- Word count of chunk_text_english, computed at ingestion time.
    -- Avoids parsing text at query time and supports sampling strategies
    -- that skip chunks once a word-count budget is exhausted.
    word_count INTEGER NOT NULL,

    UNIQUE (video_id, chunk_index)
);


CREATE TABLE youtube_comments (
    -- YouTube comment IDs are strings.
    id TEXT PRIMARY KEY,

    video_id TEXT NOT NULL REFERENCES youtube_videos(video_id) ON DELETE CASCADE,

    author TEXT,

    -- Raw scraped text, often contains HTML tags and entities from the
    -- YouTube Data API (e.g. <a href="...">, &#39;, &amp;). Never overwritten.
    text TEXT,

    -- Populated by a downstream HTML-stripping / entity-decoding stage.
    cleaned_text TEXT,
    is_cleaned   BOOLEAN NOT NULL DEFAULT FALSE,

    -- Same truncation caveat as Reddit upvotes (YouTube shows "1.2K likes").
    like_count INTEGER,

    published_date TIMESTAMP WITH TIME ZONE,

    raw_json JSONB NOT NULL
);


-- ==========================================
-- INDEXES
-- ==========================================

-- ── Reddit ──────────────────────────────

-- Fetch all comments for a given post.
CREATE INDEX idx_reddit_comments_post_id
    ON reddit_comments(post_id);

-- Fetch all direct replies under a given comment (thread reconstruction).
CREATE INDEX idx_reddit_comments_parent_id
    ON reddit_comments(parent_comment_id);

-- Slice dataset by search query / research topic.
CREATE INDEX idx_reddit_posts_source_query
    ON reddit_posts(source_query);


-- ── YouTube ─────────────────────────────

-- Fetch all comments for a given video.
CREATE INDEX idx_youtube_comments_video_id
    ON youtube_comments(video_id);

-- Slice dataset by search query / research topic.
CREATE INDEX idx_youtube_videos_source_query
    ON youtube_videos(source_query);

-- Primary access pattern for the processing pipeline: read all chunks
-- for a video in sequential order, or binary-search to a specific chunk.
CREATE INDEX idx_transcript_chunks_video_chunk
    ON transcript_chunks(video_id, chunk_index);

-- Supports cost-control sampling strategies: filter chunks by cumulative
-- word count (requires a window query, but this index makes the initial
-- video_id predicate efficient).
CREATE INDEX idx_transcript_chunks_video_wordcount
    ON transcript_chunks(video_id, word_count);
